FROM openjdk:11-jre

# Make softhsm2 available for install
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get -q update
RUN apt-get -y upgrade
# Install softhsm2
RUN apt-get install -y procps softhsm2
# Install pkcs11-tool
RUN apt-get -y install opensc
# Copy exported keys to image

# Setup softhsm
#RUN rm -rf /var/lib/softhsm/tokens && mkdir /var/lib/softhsm/tokens

ADD target/sigval-service-1.1.1-SNAPSHOT.jar /app.jar
ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000","-jar","/app.jar"]

EXPOSE 8080
EXPOSE 8443
EXPOSE 8009
EXPOSE 8008
